import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {kitchenStock as items} from './kitchen-stock.mjs';
const byName=name=>items.find(x=>x.n===name);
assert.equal(new Set(items.map(x=>x.id)).size,items.length);
assert.equal(items.filter(x=>x.n==='Gluten-free Turkish bread').length,1);
assert.equal(byName('Gluten-free Turkish bread').q,4);
assert.equal(byName('Gluten-free Turkish bread').capacity,'200 g');
for(const name of ['Rhubarb','Mesclun','Rocket','Spinach'])assert.equal(byName(name).u,'packs');
assert.equal(byName('Plain flour').q,null);
assert.equal(byName('Paper towel').q,0);
assert.equal(byName('Avocado').q,0.5);
assert.equal(byName('Avocado').allowFraction,true);
assert.equal(byName('Fries').q,2.5);
assert.equal(byName('Eggs').q,108);
for(const item of items)assert.ok(item.group,'Missing group: '+item.n);
assert.equal(byName('Lemons').c,'Fruit');assert.equal(byName('Lemons').group,'Citrus');
assert.equal(byName('Mint').group,'Herbs');assert.equal(byName('Purple carrots').group,'Root vegetables');
assert.equal(byName('Cling wrap').c,'Consumables');assert.equal(byName('Fries').c,'Frozen');
assert.equal(byName('Bacon').c,'Meat');assert.equal(byName('Sardines').c,'Seafood');
assert.equal(byName('Extra-virgin olive oil').group,'Oils');
const extension=fs.readFileSync(new URL('./local-details.js',import.meta.url),'utf8');
const functions=extension.slice(extension.indexOf('function detailsNeeded'),extension.indexOf('measuredQuantity='));
const ctx=vm.createContext({});vm.runInContext(functions,ctx);
assert.equal(ctx.readyForReorder(byName('Eggs')),false);
assert.equal(ctx.detailsNeeded(byName('Plain flour')).includes('Physical count'),true);
assert.equal(ctx.detailsNeeded(byName('Paper towel')).includes('Physical count'),false);
const complete={...byName('Avocado'),t:2,s:'Example supplier',capacity:'12 each',purchasePackConfirmed:true};
assert.equal(ctx.readyForReorder(complete),true);assert.equal(ctx.detailsNeeded(complete).length,0);
console.log(`PASS: ${items.length} distinct kitchen products; unknown counts, actual zeros, GF bread deduplication, pack units, fractional counts, missing-detail markers and reorder exclusion.`);
